IF ( LLVM_FOUND )
    INCLUDE ( HandleLLVMOptions )
    INCLUDE ( LLVMProcessSources )

    FUNCTION ( get_anydsl2_llvm_dependency_libs OUT_VAR )
        llvm_map_components_to_libraries ( ANYDSL2_LLVM_TEMP_LIBS jit native analysis )
        SET ( ${OUT_VAR} ${ANYDSL2_LLVM_TEMP_LIBS} PARENT_SCOPE )
    ENDFUNCTION ()
ELSE ()
    FUNCTION ( get_anydsl2_llvm_dependency_libs OUT_VAR )
        SET ( ${OUT_VAR} PARENT_SCOPE )
    ENDFUNCTIOn ()
ENDIF ()

IF ( WFV2_FOUND )
    FUNCTION ( get_anydsl2_wfv2_dependency_libs OUT_VAR )
        get_wfv2_llvm_dependency_libs ( ANYDSL2_WFV2_TEMP_LIBS )
        SET ( ${OUT_VAR} ${ANYDSL2_WFV2_TEMP_LIBS} PARENT_SCOPE )
    ENDFUNCTION ()
ELSE ()
    FUNCTION ( get_anydsl2_wfv2_dependency_libs OUT_VAR )
        SET ( ${OUT_VAR} PARENT_SCOPE )
    ENDFUNCTION ()
ENDIF ()

FUNCTION ( get_anydsl2_dependency_libs OUT_VAR )
    get_anydsl2_llvm_dependency_libs ( ANYDSL2_LLVM_TEMP_LIBS )
    get_anydsl2_wfv2_dependency_libs ( ANYDSL2_WFV2_TEMP_LIBS )
    SET ( ${OUT_VAR} ${ANYDSL2_LLVM_TEMP_LIBS} ${ANYDSL2_WFV2_TEMP_LIBS} PARENT_SCOPE )
ENDFUNCTION ()

