IF ( LLVM_FOUND )
    FUNCTION ( get_thorin_llvm_dependency_libs OUT_VAR )
        llvm_map_components_to_libnames ( THORIN_LLVM_TEMP_LIBS core mc native ipo irreader bitreader bitwriter scalaropts support target )
        SET ( ${OUT_VAR} ${THORIN_LLVM_TEMP_LIBS} PARENT_SCOPE )
    ENDFUNCTION ()
ELSE ()
    FUNCTION ( get_thorin_llvm_dependency_libs OUT_VAR )
        SET ( ${OUT_VAR} PARENT_SCOPE )
    ENDFUNCTION ()
ENDIF ()

IF ( RV_FOUND )
    FUNCTION ( get_thorin_rv_dependency_libs OUT_VAR )
        get_rv_llvm_dependency_libs ( THORIN_RV_TEMP_LIBS )
        SET ( ${OUT_VAR} ${RV_LIBRARIES} ${THORIN_RV_TEMP_LIBS} PARENT_SCOPE )
    ENDFUNCTION ()
ELSE ()
    FUNCTION ( get_thorin_rv_dependency_libs OUT_VAR )
        SET ( ${OUT_VAR} PARENT_SCOPE )
    ENDFUNCTION ()
ENDIF ()

FUNCTION ( get_thorin_dependency_libs OUT_VAR )
    get_thorin_llvm_dependency_libs ( THORIN_LLVM_TEMP_LIBS )
    get_thorin_rv_dependency_libs ( THORIN_RV_TEMP_LIBS )
    SET ( ${OUT_VAR} ${THORIN_LLVM_TEMP_LIBS} ${THORIN_RV_TEMP_LIBS} PARENT_SCOPE )
ENDFUNCTION ()
