#ifndef THORIN_ARITHOP
#error "define THORIN_ARITHOP before including this file"
#endif

THORIN_ARITHOP(add)
THORIN_ARITHOP(sub)
THORIN_ARITHOP(mul)
THORIN_ARITHOP(sdiv)
THORIN_ARITHOP(udiv)
THORIN_ARITHOP(srem)
THORIN_ARITHOP(urem)

THORIN_ARITHOP(fadd)
THORIN_ARITHOP(fsub)
THORIN_ARITHOP(fmul)
THORIN_ARITHOP(fdiv)
THORIN_ARITHOP(frem)

THORIN_ARITHOP(and)
THORIN_ARITHOP(or)
THORIN_ARITHOP(xor)
THORIN_ARITHOP(shl)
THORIN_ARITHOP(lshr)
THORIN_ARITHOP(ashr)

#undef THORIN_ARITHOP
