#ifndef THORIN_MATHOP
#error "define THORIN_MATHOP before including this file"
#endif

THORIN_MATHOP(fabs)
THORIN_MATHOP(copysign)
THORIN_MATHOP(signbit)
THORIN_MATHOP(round)
THORIN_MATHOP(floor)
THORIN_MATHOP(ceil)
THORIN_MATHOP(fmin)
THORIN_MATHOP(fmax)
THORIN_MATHOP(cos)
THORIN_MATHOP(sin)
THORIN_MATHOP(tan)
THORIN_MATHOP(acos)
THORIN_MATHOP(asin)
THORIN_MATHOP(atan)
THORIN_MATHOP(atan2)
THORIN_MATHOP(sqrt)
THORIN_MATHOP(cbrt)
THORIN_MATHOP(pow)
THORIN_MATHOP(exp)
THORIN_MATHOP(exp2)
THORIN_MATHOP(log)
THORIN_MATHOP(log2)
THORIN_MATHOP(log10)

#undef THORIN_MATHOP
