#ifdef THORIN_ALL_TYPE
#define THORIN_S_TYPE(T)  THORIN_ALL_TYPE(T)
#define THORIN_U_TYPE(T)  THORIN_ALL_TYPE(T)
#define THORIN_QS_TYPE(T) THORIN_ALL_TYPE(T)
#define THORIN_QU_TYPE(T) THORIN_ALL_TYPE(T)
#define THORIN_F_TYPE(T)  THORIN_ALL_TYPE(T)
#define THORIN_QF_TYPE(T) THORIN_ALL_TYPE(T)
#endif

#ifndef THORIN_S_TYPE
#define THORIN_S_TYPE(T)
#endif

THORIN_WU_TYPE(s1)
THORIN_WU_TYPE(s8)
THORIN_WU_TYPE(s16)
THORIN_WU_TYPE(s32)
THORIN_WU_TYPE(s64)

#ifndef THORIN_U_TYPE
#define THORIN_U_TYPE(T)
#endif

THORIN_WS_TYPE(u1)
THORIN_WS_TYPE(u8)
THORIN_WS_TYPE(u16)
THORIN_WS_TYPE(u32)
THORIN_WS_TYPE(u64)

#ifndef THORIN_QS_TYPE
#define THORIN_QS_TYPE(T)
#endif

THORIN_WU_TYPE(qs1)
THORIN_WU_TYPE(qs8)
THORIN_WU_TYPE(qs16)
THORIN_WU_TYPE(qs32)
THORIN_WU_TYPE(qs64)

#ifndef THORIN_QU_TYPE
#define THORIN_QU_TYPE(T)
#endif

THORIN_WS_TYPE(qu1)
THORIN_WS_TYPE(qu8)
THORIN_WS_TYPE(qu16)
THORIN_WS_TYPE(qu32)
THORIN_WS_TYPE(qu64)

#ifndef THORIN_F_TYPE
#define THORIN_F_TYPE(T)
#endif

THORIN_F_TYPE(f32)
THORIN_F_TYPE(f64)

#ifndef THORIN_QF_TYPE
#define THORIN_QF_TYPE(T)
#endif

THORIN_F_TYPE(qf32)
THORIN_F_TYPE(qf64)

#undef THORIN_S_TYPE
#undef THORIN_U_TYPE
#undef THORIN_QS_TYPE
#undef THORIN_QU_TYPE
#undef THORIN_F_TYPE
#undef THORIN_QF_TYPE
#undef THORIN_ALL_TYPE
