#ifdef THORIN_ALL_TYPE
#define THORIN_U_TYPE(T)  THORIN_ALL_TYPE(T)
#define THORIN_FF_TYPE(T) THORIN_ALL_TYPE(T)
#define THORIN_PF_TYPE(T) THORIN_ALL_TYPE(T)
#endif

#ifndef THORIN_U_TYPE
#define THORIN_U_TYPE(T)
#endif

THORIN_U_TYPE(u1)
THORIN_U_TYPE(u8)
THORIN_U_TYPE(u16)
THORIN_U_TYPE(u32)
THORIN_U_TYPE(u64)

#ifndef THORIN_FF_TYPE
#define THORIN_FF_TYPE(T)
#endif

THORIN_F_TYPE(ff32)
THORIN_F_TYPE(ff64)

#ifndef THORIN_PF_TYPE
#define THORIN_PF_TYPE(T)
#endif

THORIN_F_TYPE(pf32)
THORIN_F_TYPE(pf64)

#undef THORIN_U_TYPE
#undef THORIN_FF_TYPE
#undef THORIN_F_TYPE
#undef THORIN_ALL_TYPE
