#ifdef THORIN_ALL_TYPE
#define THORIN_P_TYPE(T, M) THORIN_ALL_TYPE(T, M)
#define THORIN_Q_TYPE(T, M) THORIN_ALL_TYPE(T, M)
#define THORIN_BOOL_TYPE(T, M) THORIN_ALL_TYPE(T, M)
#endif

#ifdef THORIN_P_TYPE
#define THORIN_PS_TYPE(T, M) THORIN_P_TYPE(T, M)
#define THORIN_PU_TYPE(T, M) THORIN_P_TYPE(T, M)
#define THORIN_PF_TYPE(T, M) THORIN_P_TYPE(T, M)
#endif

#ifdef THORIN_Q_TYPE
#define THORIN_QS_TYPE(T, M) THORIN_Q_TYPE(T, M)
#define THORIN_QU_TYPE(T, M) THORIN_Q_TYPE(T, M)
#define THORIN_QF_TYPE(T, M) THORIN_Q_TYPE(T, M)
#endif

#ifdef THORIN_I_TYPE
#define THORIN_PS_TYPE(T, M) THORIN_I_TYPE(T, M)
#define THORIN_PU_TYPE(T, M) THORIN_I_TYPE(T, M)
#define THORIN_QS_TYPE(T, M) THORIN_I_TYPE(T, M)
#define THORIN_QU_TYPE(T, M) THORIN_I_TYPE(T, M)
#endif

#ifdef THORIN_F_TYPE
#define THORIN_PF_TYPE(T, M) THORIN_F_TYPE(T, M)
#define THORIN_QF_TYPE(T, M) THORIN_F_TYPE(T, M)
#endif

#ifndef THORIN_BOOL_TYPE
#define THORIN_BOOL_TYPE(T, M)
#endif

THORIN_BOOL_TYPE(bool, bool)

#ifndef THORIN_PS_TYPE
#define THORIN_PS_TYPE(T, M)
#endif

THORIN_PS_TYPE(ps8, s8)
THORIN_PS_TYPE(ps16, s16)
THORIN_PS_TYPE(ps32, s32)
THORIN_PS_TYPE(ps64, s64)

#ifndef THORIN_PU_TYPE
#define THORIN_PU_TYPE(T, M)
#endif

THORIN_PU_TYPE(pu8, u8)
THORIN_PU_TYPE(pu16, u16)
THORIN_PU_TYPE(pu32, u32)
THORIN_PU_TYPE(pu64, u64)

#ifndef THORIN_QS_TYPE
#define THORIN_QS_TYPE(T, M)
#endif

THORIN_QS_TYPE(qs8, s8)
THORIN_QS_TYPE(qs16, s16)
THORIN_QS_TYPE(qs32, s32)
THORIN_QS_TYPE(qs64, s64)

#ifndef THORIN_QU_TYPE
#define THORIN_QU_TYPE(T, M)
#endif

THORIN_QU_TYPE(qu8, u8)
THORIN_QU_TYPE(qu16, u16)
THORIN_QU_TYPE(qu32, u32)
THORIN_QU_TYPE(qu64, u64)

#ifndef THORIN_PF_TYPE
#define THORIN_PF_TYPE(T, M)
#endif

THORIN_PF_TYPE(pf16, f16)
THORIN_PF_TYPE(pf32, f32)
THORIN_PF_TYPE(pf64, f64)

#ifndef THORIN_QF_TYPE
#define THORIN_QF_TYPE(T, M)
#endif

THORIN_QF_TYPE(qf16, f16)
THORIN_QF_TYPE(qf32, f32)
THORIN_QF_TYPE(qf64, f64)

#undef THORIN_PS_TYPE
#undef THORIN_PU_TYPE
#undef THORIN_QS_TYPE
#undef THORIN_QU_TYPE
#undef THORIN_PF_TYPE
#undef THORIN_QF_TYPE
#undef THORIN_BOOL_TYPE
#undef THORIN_P_TYPE
#undef THORIN_Q_TYPE
#undef THORIN_I_TYPE
#undef THORIN_F_TYPE
#undef THORIN_ALL_TYPE
