#ifndef ANYDSL_ARITHOP
#error "define ANYDSL_ARITHOP before including this file"
#endif

ANYDSL_ARITHOP(add)
ANYDSL_ARITHOP(sub)
ANYDSL_ARITHOP(mul)
ANYDSL_ARITHOP(sdiv)
ANYDSL_ARITHOP(udiv)
ANYDSL_ARITHOP(srem)
ANYDSL_ARITHOP(urem)

ANYDSL_ARITHOP(fadd)
ANYDSL_ARITHOP(fsub)
ANYDSL_ARITHOP(fmul)
ANYDSL_ARITHOP(fdiv)
ANYDSL_ARITHOP(frem)

ANYDSL_ARITHOP(and)
ANYDSL_ARITHOP(or)
ANYDSL_ARITHOP(xor)
ANYDSL_ARITHOP(shl)
ANYDSL_ARITHOP(lshr)
ANYDSL_ARITHOP(ashr)

#undef ANYDSL_ARITHOP
