#ifndef ANYDSL2_ARITHOP
#error "define ANYDSL2_ARITHOP before including this file"
#endif

ANYDSL2_ARITHOP(add)
ANYDSL2_ARITHOP(sub)
ANYDSL2_ARITHOP(mul)
ANYDSL2_ARITHOP(sdiv)
ANYDSL2_ARITHOP(udiv)
ANYDSL2_ARITHOP(srem)
ANYDSL2_ARITHOP(urem)

ANYDSL2_ARITHOP(fadd)
ANYDSL2_ARITHOP(fsub)
ANYDSL2_ARITHOP(fmul)
ANYDSL2_ARITHOP(fdiv)
ANYDSL2_ARITHOP(frem)

ANYDSL2_ARITHOP(and)
ANYDSL2_ARITHOP(or)
ANYDSL2_ARITHOP(xor)
ANYDSL2_ARITHOP(shl)
ANYDSL2_ARITHOP(lshr)
ANYDSL2_ARITHOP(ashr)

#undef ANYDSL2_ARITHOP
