#ifndef ANYDSL2_CONVOP
#error "define ANYDSL2_CONVOP before including this file"
#endif

ANYDSL2_CONVOP(trunc)
ANYDSL2_CONVOP(zext)
ANYDSL2_CONVOP(sext)
ANYDSL2_CONVOP(stof)
ANYDSL2_CONVOP(utof)
ANYDSL2_CONVOP(ftrunc)
ANYDSL2_CONVOP(fext)
ANYDSL2_CONVOP(ftos)
ANYDSL2_CONVOP(ftou)
ANYDSL2_CONVOP(bitcast)
ANYDSL2_CONVOP(inttoptr)
ANYDSL2_CONVOP(ptrtoint)

#undef ANYDSL2_CONVOP
